### ISSUE TITLE
No se puede realizar inventario, ni movimientos para productos con stock negativo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1015]
Probado en runbot: http://3116328-8-0-437424.runbot2.odoo-community.org/
Se reproduce en nuestro entorno demo

Al intentar validar un inventario, o confirmar un pedido de compra de un producto que tiene stock negativo da el error:
MissingError
One of the documents you are trying to access has been deleted, please try again after refreshing.

---

En runbot de OCA no se reproduce. 
He intentado detectar qué módulo es el que está provocando el error pero no lo he conseguido. 

Creando un movimiento manualmente desde una ubicación interna a una virtual, funciona perfecto
Creando un movimiento manualmente desde una ubicación virtual a una interna, se produce también el error.

**Comment by anajuaristi** [comment]
@Daniel-CA @agaldona @alfredoavanzosc --> Este error es bastante crítico porque simplemente haciendo "forzar disponibilidad" en cualquier albarán de salida u orden de fabricación nos queda stock negativo y no hay forma de volver a ponerle stock positivo al producto. ¿Podría cualquiera de vosotros mirarlo de forma urgente? Al menos saber cual de los módulos está provocando el problema.
Debe venir de algo que se ha mergeado en las últimas semanas. Como ya he dicho antes, en el runbot de OCA no se reproduce. Solo en nuestro demo y en el runbot de wip.

@pedrobaeza alguna pista de por donde puede venir? 
Gracias

**Comment by pedrobaeza** [comment]
Pero me tienes que decir los pasos para llegar a ese quant negativo.

**Comment by anajuaristi** [comment]
Cualquier quant negativo. Por ejemplo, haces un albarán de salida y fuerzas disponibilidad. O bien en fabricación, fuerzas disponibilidad
Luego intentas hacer inventario de cualquier producto que tenga stock negativo y te da el error. 

También si intentas una compra o simplemente realizar un movimiento con ubicación origen virtual te da el mismo error

**Comment by pedrobaeza** [comment]
Ah, vale, ya te he entendido. Y qué error aparece?

**Comment by anajuaristi** [comment]
El genérico este de que se ha borrado algo... 
MissingError
One of the documents you are trying to access has been deleted, please try again after refreshing.

**Comment by pedrobaeza** [comment]
Ya, claro, ahí te enmascara el resto de la traza... lo has podido reproducir en demo.odoomrp.com?

**Comment by anajuaristi** [comment]
Si. En demo se reproduce. Ahí fue donde nos salió en la bbdd septiembre_2015.
Yo creo que tiene algo que ver con los quants... pero no veo relación con ningún módulo. Ya te digo que en el runbot de la comunidad no da. Solo en nuestro wip. Supongo que habrá que debugear para pillarlo.
Espera que lo pruebo en utils y te digo

**Comment by anajuaristi** [comment]
En utils va bien. Es algo que está en wip y que se haya mergeado recientemente.

**Comment by pedrobaeza** [comment]
OK, si es reproducible en demo puedo mirar el log para ver la traza completa. Ahora lo pruebo y te cuento.

**Comment by anajuaristi** [comment]
Mira el inventario "Uno". Si le das validar, te sale el error en demo bbdd septiembre_2015. Digo para que no andes generando datos para la prueba.

**Comment by pedrobaeza** [comment]
Ésta es la traza completa:

```
Traceback (most recent call last):
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock/stock.py", line 2729, in action_done
    self.post_inventory(cr, uid, inv, context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock_account/stock_account.py", line 41, in post_inventory
    return super(stock_inventory, self).post_inventory(cr, uid, inv, context=ctx)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock/stock.py", line 2737, in post_inventory
    move_obj.action_done(cr, uid, [x.id for x in inv.move_ids if x.state != 'done'], context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock_account/stock_account.py", line 272, in action_done
    res = super(stock_move, self).action_done(cr, uid, ids, context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock/stock.py", line 2455, in action_done
    quant_obj.quants_move(cr, uid, quants, move, move.location_dest_id, lot_id=move.restrict_lot_id.id, owner_id=move.restrict_partner_id.id, context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock/stock.py", line 427, in quants_move
    self._quant_reconcile_negative(cr, uid, quant, move, context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock/stock.py", line 602, in _quant_reconcile_negative
    self._price_update(cr, uid, solved_quant_ids, solving_quant.cost, context=context)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/stock_account/stock_account.py", line 101, in _price_update
    if quant.product_id.cost_method == 'real' and quant.location_id.usage != 'internal':
  File "/opt/odoo/demo_odoomrp/core/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/opt/odoo/demo_odoomrp/core/openerp/models.py", line 5964, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/demo_odoomrp/core/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')
```

En principio, no aparece ningún módulo personalizado implicado.

**Comment by anajuaristi** [comment]
¿Puede estar relacionado con los costes? Digo por esto, igual estamos heredando stock_account o algo. Por dar alguna pista... no sé.

```
 File "/opt/odoo/demo_odoomrp/core/addons/stock_account/stock_account.py", line 101, in _price_update
    if quant.product_id.cost_method == 'real' and quant.location_id.usage != 'internal':
```

**Comment by pedrobaeza** [comment]
Acaba de funcionarme cuando he reiniciado el servicio. Creo que era un bug del propio Odoo. Haz un rebuild en odoomrp-wip y prueba de nuevo.

**Comment by anajuaristi** [comment]
Ok. Lanzado rebuild. 
Pruebo mañana :+1:

**Comment by anajuaristi** [comment]
El error en runbot se sigue reproduciendo. Probado en:
http://3116882-8-0-503356.runbot1.odoo-community.org/

Con el producto [A2323] iPad Retina Display (16 GB, White, 2.4 GHz) que tiene 8 unidades negativas.
Directamente ir a la ficha de producto y tratando de ponerle más de cero unidades, se reproduce el error.

**Comment by oihane** [comment]
El modulo que crea los problemas es el `stock_inventory_import`

estoy con ello

**Comment by oihane** [comment]
Con una copia en local del runbot:

```
2015-10-14 15:24:16,249 12433 ERROR runbot_20151013 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/avanzosc/Odoo/OCB-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/avanzosc/Odoo/OCB-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/avanzosc/Odoo/OCB-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/wizard/stock_change_product_qty.py", line 120, in change_product_qty
    inventory_obj.action_done(cr, uid, [inventory_id], context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/avanzosc/Odoo/linked_addons/stock_inventory_import/models/stock_inventory.py", line 82, in action_done
    super(StockInventory, inventory).action_done()
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/stock.py", line 2729, in action_done
    self.post_inventory(cr, uid, inv, context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock_account/stock_account.py", line 41, in post_inventory
    return super(stock_inventory, self).post_inventory(cr, uid, inv, context=ctx)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/stock.py", line 2737, in post_inventory
    move_obj.action_done(cr, uid, [x.id for x in inv.move_ids if x.state != 'done'], context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock_account/stock_account.py", line 272, in action_done
    res = super(stock_move, self).action_done(cr, uid, ids, context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/stock.py", line 2455, in action_done
    quant_obj.quants_move(cr, uid, quants, move, move.location_dest_id, lot_id=move.restrict_lot_id.id, owner_id=move.restrict_partner_id.id, context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/stock.py", line 427, in quants_move
    self._quant_reconcile_negative(cr, uid, quant, move, context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock/stock.py", line 602, in _quant_reconcile_negative
    self._price_update(cr, uid, solved_quant_ids, solving_quant.cost, context=context)
  File "/home/avanzosc/Odoo/OCB-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc/Odoo/OCB-server/addons/stock_account/stock_account.py", line 101, in _price_update
    if quant.product_id.cost_method == 'real' and quant.location_id.usage != 'internal':
  File "/home/avanzosc/Odoo/OCB-server/openerp/fields.py", line 825, in __get__
    return record._cache[self]
  File "/home/avanzosc/Odoo/OCB-server/openerp/models.py", line 5996, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/avanzosc/Odoo/OCB-server/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')
```

Resulta que el error se da exactamente en:

```
  File "/home/avanzosc/Odoo/OCB-server/addons/stock_account/stock_account.py", line 101, in _price_update
    if quant.product_id.cost_method == 'real' and quant.location_id.usage != 'internal':
```

Si que devuelve un valor en quant.product_id, pero es el cost_method el que da MissingError y no sé porque a veces funciona con el debugger y otras no, pero sin él siempre falla.

Probé quitando el modulo **stock_inventory_import** y funciono, pero no veo que es lo que puede causar ese error. @Daniel-CA dice que el quitó el modulo **stock_quant_merge**  y también le funciono.

Lo que he hecho es de alguna manera hacer que el producto mencionado por Ana tenga un valor (quantity on hand) negativo, y desde la misma pagina de producto actualizar ese valor.

Dato a tener en cuenta: `cost_method` se define en el `product_template` y es de tipo `property` se puede ver en el modulo `stock_account`

**Comment by pedrobaeza** [comment]
Esto está solucionado, no?

**Comment by anajuaristi** [comment]
Si, validado que en wip ya no da. 
:+1: 
Lo único que sí sigue dando en nuestro entorno. Supongo que hace bastante que no actualizamos demo.

**Comment by pedrobaeza** [comment]
OK, cierro.
