### ISSUE TITLE
Module procurement_purchase_no_grouping not working

### ISSUE THREAD

**Issue by NL66278** [odoomrp/odoomrp-wip#1141]
Need this module to prevent merging purchase order lines. But does not work. Failing also on rununit tests: 
2016-01-31 14:57:03,137 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: test_procurement_no_grouping_line_purchase (openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping.TestProcurementPurchaseNoGrouping)
2016-01-31 14:57:03,817 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: FAIL
2016-01-31 14:57:03,817 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: test_procurement_no_grouping_order_purchase (openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping.TestProcurementPurchaseNoGrouping)
2016-01-31 14:57:04,561 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: FAIL
2016-01-31 14:57:04,561 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: ======================================================================
2016-01-31 14:57:04,561 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: FAIL: test_procurement_no_grouping_line_purchase (openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping.TestProcurementPurchaseNoGrouping)
2016-01-31 14:57:04,561 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: Traceback (most recent call last):
2016-01-31 14:57:04,561 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: `File "/home/openeyedev/var/projects/oe_intervlag_80/buildout_tst/parts/odoomrp/procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py", line 62, in test_procurement_no_grouping_line_purchase
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping:`     'Procured purchase orders lines are the same')
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: `AssertionError: purchase.order.line(324,) == purchase.order.line(324,) : Procured purchase orders lines are the same
2016-01-31 14:57:04,562 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: ======================================================================
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: FAIL: test_procurement_no_grouping_order_purchase (openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping.TestProcurementPurchaseNoGrouping)
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: Traceback (most recent call last):
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping:`   File "/home/openeyedev/var/projects/oe_intervlag_80/buildout_tst/parts/odoomrp/procurement_purchase_no_grouping/tests/test_procurement_purchase_no_grouping.py", line 74, in test_procurement_no_grouping_order_purchase
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: `'Procured purchase orders are the same')
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping:` AssertionError: purchase.order(222,) == purchase.order(222,) : Procured purchase orders are the same
2016-01-31 14:57:04,562 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: Ran 3 tests in 2.287s
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping: FAILED
2016-01-31 14:57:04,562 11694 INFO oerivldem80 openerp.addons.procurement_purchase_no_grouping.tests.test_procurement_purchase_no_grouping:  (failures=2)
2016-01-31 14:57:04,562 11694 ERROR oerivldem80 openerp.modules.module: Module procurement_purchase_no_grouping: 2 failures, 0 errors

**Comment by NL66278** [comment]
On further analysis this seems due to an incompatibility with the procurement_jit module. This makes the procurement already runs in the setup method of the test, before giving procured_purchase_grouping another value than the default 'standard'.

**Comment by pedrobaeza** [comment]
It seems so... I can include the known incompatibility in the README or are you planning to improve the module with this compatibility? You can also take the occasion to move it to OCA.

**Comment by NL66278** [comment]
Actually it are only the tests IMHO that need to be adopted, IRL products will have the right category before being procured/purchased. OK to move module to OCA. Would purchase-workflow be the right repository?

**Comment by pedrobaeza** [comment]
:+1: for purchase-workflow.

**Comment by NL66278** [comment]
Is is now PR https://github.com/OCA/purchase-workflow/pull/209
