### ISSUE TITLE
No puedo instalar mrp_subcontracting en Odoo 9

### ISSUE THREAD

**Issue by quintanapablo** [odoomrp/odoomrp-wip#1213]
Hola Pedro/OdooMRP,

Encontré sus videos y el mrp_subcontracting es lo que necesitamos para agregar operaciones que son externas. Desafortunadamente no logro instalar el módulo de la versión 9.0. Después de habilitar “instalable=True” en **openerp**.py y tratar de instalar tengo el siguiente error cuando intento mrp_operations_extensions. Alguna razón por que la versión 9.0 no viene habilitada para instalarse? Puedo instalar el módulo para 8.0?

Muchas gracias.

`Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/odoo/odoo-server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/odoo/odoo-server/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/odoo/odoo-server/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/openerp/modules/loading.py", line 98, in _load_data
   tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1142, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4342, in _create
    recs._validate_fields(vals)
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `mrp.workcenter.form.inh`
[view_id: 882, xml_id: n/a, model: mrp.workcenter, parent_id: 608]
None" while parsing /odoo/custom/addons/odoo-apps/mrp_operations_extension/views/mrp_workcenter_view.xml:4, near
<record id="mrp_workcenter_form_view_inh" model="ir.ui.view">
            <field name="name">mrp.workcenter.form.inh</field>
            <field name="model">mrp.workcenter</field>
            <field name="inherit_id" ref="mrp.mrp_workcenter_view"/>
            <field name="arch" type="xml">
                <data><field name="time_start" position="after">
                    <field name="pre_op_product"/>
                </field>
                <field name="time_stop" position="after">
                    <field name="post_op_product"/>
                </field>
                <xpath expr="//page[@string='General Information']" position="after">
                   <page string="Operators" groups="mrp_operations_extension.group_mrp_workers">
                        <group colspan="4">
                            <field name="op_number"/>
                            <field name="op_avg_cost"/>
                        </group>
                        <field name="operators"/>
                    </page>
                    <page string="Routing Operations">
                        <field name="rt_operations" nolabel="1"/>
                    </page>
               </xpath>
            </data></field>
        </record>`

**Comment by pedrobaeza** [comment]
El módulo no está disponible en v9.
