### ISSUE TITLE
product_variants

### ISSUE THREAD

**Issue by jaferrer** [odoomrp/odoomrp-wip#1219]
Hello,

After upgrading to the latest,  cannot create new product variants.

A constraint message appears 'Mixing apples and oranges: product.attribute.line(1,) - product.attribute(1,)'

Before it worked fine.

Now checking out '380b649230760107748f86970662ce4c2c699cb1' (the previous one) and works again !!

Traceback (most recent call last):
  File "/opt/apps/v8/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/apps/v8/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/apps/v8/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/apps/v8/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/apps/v8/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/apps/v8/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/apps/v8/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/addons/stock/product.py", line 502, in write
    return super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/apps/v8/odoomrp-wip/product_variants_no_automatic_creation/models/product_template.py", line 41, in write
    res = super(ProductTemplate, self).write(values)
  File "/opt/apps/v8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/apps/v8/odoo/addons/product/product.py", line 774, in write
    self.create_variant_ids(cr, uid, ids, context=context)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/apps/v8/odoomrp-wip/product_variants_no_automatic_creation/models/product_template.py", line 63, in create_variant_ids
    super(ProductTemplate, tmpl).create_variant_ids()
  File "/opt/apps/v8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/apps/v8/odoo/addons/product/product.py", line 727, in create_variant_ids
    id = product_obj.create(cr, uid, values, context=ctx)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/apps/v8/odoomrp-wip/product_variants_no_automatic_creation/models/product_product.py", line 98, in create
    return super(ProductProduct, obj).create(vals)
  File "/opt/apps/v8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/apps/v8/odoo/addons/product/product.py", line 1199, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/apps/v8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/models.py", line 4094, in create
    record = self.browse(self._create(old_vals))
  File "/opt/apps/v8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/apps/v8/odoo/openerp/models.py", line 4285, in _create
    recs._validate_fields(vals)
  File "/opt/apps/v8/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/apps/v8/odoo/openerp/models.py", line 1281, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ValidationError: ('ValidateError', u'Error while validating constraint\n\nValueError\nMixing apples and oranges: product.attribute.line(1,) - product.attribute(1,)')
2016-05-09 14:48:39,464 5283 INFO TEST werkzeug: 127.0.0.1 - - [09/May/2016 14:48:39] "POST /web/dataset/call_kw/product.template/write HTTP/1.1" 200 -

**Comment by pedrobaeza** [comment]
You should have a mix of outdated modules, but it's working as expected on our side. Please check also on runbot.

**Comment by jaferrer** [comment]
Same behaviour in runbot.

**Comment by pedrobaeza** [comment]
Please indicate the steps to get the error.

**Comment by jaferrer** [comment]
Go to runbot, install module "sale_product_variants"

In products - choose Ipad Mini
go to variants select "create them automatically" , add "color" attribute wtih value  "white", try to save changes
A constraint windows appears

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoomrp/odoomrp-wip/commit/c7eaa3e4aa128cbf2fe328782a6e9820a3c8f5be
