### ISSUE TITLE
[v9] [mrp_operations_extension] Problem installing

### ISSUE THREAD

**Issue by lrmoreno007** [odoomrp/odoomrp-wip#1304]
Hi all, I've a problem when install this module, the installation never finish and only I can cancel installation. If I change "'installable': False" to True, I receive this message:

Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 648, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 685, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 321, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 314, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 964, in __call__
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 514, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 892, in call_button
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 880, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\module\wizard\base_module_upgrade.py", line 87, in upgrade_module
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\modules\loading.py", line 98, in _load_data
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 852, in convert_file
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 935, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 802, in parse
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 805, in parse
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 700, in _tag_record
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 783, in id_get
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\convert.py", line 794, in model_id_get
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_model.py", line 984, in xmlid_to_res_model_res_id
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 250, in wrapper
  File "<string>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\cache.py", line 85, in lookup
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_model.py", line 974, in xmlid_lookup
ParseError: "External ID not found in the system: mrp_byproduct.mrp_subproduct_view" while parsing file:///C:/Program%20Files%20(x86)/Odoo%209.0/server/openerp/addons/mrp_operations_extension/views/mrp_bom_view.xml:4, near
<record id="mrp_subproduct_view_inherit" model="ir.ui.view">
            <field name="name">mrp.bom.sub.product</field>
            <field name="model">mrp.bom</field>
            <field name="inherit_id" ref="mrp_byproduct.mrp_subproduct_view"/>
            <field name="arch" type="xml">
                <xpath expr="//field[@name='sub_products']/tree/field[@name='product_id']" position="after">
                    <field name="operation" domain="[('routing_id', '=', parent.routing_id)]"/>
                </xpath>
                <xpath expr="//field[@name='sub_products']/form/field[@name='product_id']" position="after">
                    <field name="operation" domain="[('routing_id', '=', parent.routing_id)]"/>
                </xpath>
            </field>
        </record>

Please help.

**Comment by lrmoreno007** [comment]
I activate Subproducts and now:

```
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 648, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 685, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 321, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 314, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 964, in __call__
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 514, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 892, in call_button
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 880, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 98, in _load_data
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\tools\convert.py", line 852, in convert_file
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\tools\convert.py", line 935, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\tools\convert.py", line 802, in parse
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\tools\convert.py", line 805, in parse
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\tools\convert.py", line 708, in _tag_record
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_model.py", line 1144, in _update
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_ui_view.py", line 360, in create
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 354, in old_api
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\models.py", line 4157, in create
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 490, in new_api
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\models.py", line 4354, in _create
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\models.py", line 1271, in _validate_fields
ParseError: "Invalid view definition

Detalles de error:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `mrp.workcenter.form.inh`
[view_id: 1200, xml_id: n/a, model: mrp.workcenter, parent_id: 604]
None" while parsing file:///C:/Program%20Files%20(x86)/Odoo%209.0/server/openerp/addons/mrp_operations_extension/views/mrp_workcenter_view.xml:4, near
<record id="mrp_workcenter_form_view_inh" model="ir.ui.view">
            <field name="name">mrp.workcenter.form.inh</field>
            <field name="model">mrp.workcenter</field>
            <field name="inherit_id" ref="mrp.mrp_workcenter_view"/>
            <field name="arch" type="xml">
                <data><field name="time_start" position="after">
                    <field name="pre_op_product"/>
                </field>
                <field name="time_stop" position="after">
                    <field name="post_op_product"/>
                </field>
                <xpath expr="//page[@string='General Information']" position="after">
                    <page string="Operators" groups="mrp_operations_extension.group_mrp_workers">
                        <group colspan="4">
                            <field name="op_number"/>
                            <field name="op_avg_cost"/>
                        </group>
                        <field name="operators"/>
                    </page>
                    <page string="Routing Operations">
                        <field name="rt_operations" nolabel="1"/>
                    </page>
                </xpath>
            </data></field>
        </record>


```

**Comment by pedrobaeza** [comment]
Modules are not migrated to v9. That's the reason why they don't work.

**Comment by lrmoreno007** [comment]
But I give it from v.9 branch.

v9 Branch isn't migrated to v9?

**Comment by lrmoreno007** [comment]
OK, It's semi-working 

1- Applying this Pull Request https://github.com/odoomrp/odoomrp-wip/pull/1253
2- Commenting in **openerp**.py line 48:  #"views/mrp_bom_view.xml",

This view fail to me: "Operation" field doesn't exist.

I'm working with a v9 database, it isn't migrated. Must be the problem.

Un saludo y gracias.

**Comment by pedrobaeza** [comment]
The branch is there as a host for the migration, but there's a reason for being not installable.
