### ISSUE TITLE
ProgrammingError: can't adapt type 'stock.location'

### ISSUE THREAD

**Issue by kkoci** [odoomrp/odoomrp-wip#1325]
Hola, tengo un .csv , con code, location, y quantity

Pero al intentar importar me sale ésto:

> 2016-11-02 23:18:38,659 16865 ERROR moto_backup openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/kristian/odoov9/odoo-9.0/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/kristian/odoov9/odoo-9.0/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/kristian/odoov9/odoo-9.0/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 421, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 425, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/kristian/odoov9/motostion_addons/odoomrp-wip-9.0/stock_inventory_import/wizard/import_inventory.py", line 89, in action_import
    inv_imporline_obj.create(val)
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/models.py", line 4301, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/kristian/odoov9/odoo-9.0/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/kristian/odoov9/odoo-9.0/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: can't adapt type 'stock.location'

¿Alguna idea de ésto?

¿Será por el .csv?

Por favor, es urgente

Estoy en Odoo v9 community, Gracias

**Comment by anajuaristi** [comment]
Odoo v9.
Los módulos de odoomrp son para V8. Si lo quieres usar, tendrías que migrar el módulo como ya te dije en la lista de la comunidad.

**Comment by kkoci** [comment]
Ok, voy a arreglarlo entonces

Yo le había cambiado algunas cosas y se instaló correctamente, pero obviamente hay algo más que revisar

Gracias

**Comment by kkoci** [comment]
¿Puedo hacer pull requests?

**Comment by kkoci** [comment]
Ya lo arreglé, hice un pull request

Un saludo

**Comment by anajuaristi** [comment]
Te lo he mergeado.
Gracias por la contribución.

Cierro el issue
