### ISSUE TITLE
Error en stock_picking_taxes [Version 9.0]

### ISSUE THREAD

**Issue by albokasoft** [odoomrp/odoomrp-wip#1410]
Al instalar el modulo da el siguiente error

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 136, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 203, in setup_models
    model._setup_complete(cr, SUPERUSER_ID)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3091, in _setup_complete
    field.setup_triggers(self.env)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 644, in setup_triggers
    self._add_trigger(env, path_str)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 628, in _add_trigger
    field = model._fields[name]
KeyError: 'product_uos_qty'

**Comment by pedrobaeza** [comment]
El módulo no está migrado a dicha versión.

**Comment by albokasoft** [comment]
Hola Pedro, teneis alguna previsión para migralo a la 9 o me puedes dar una pista de como solucionar el error que da?

muchas gracias

**Comment by pedrobaeza** [comment]
No, utiliza stock_valued_picking_report de OCA

**Comment by albokasoft** [comment]
Hola Pedro, no me ha quedado claro. ¿A que te refieres? ¿A que puedo usar el modulo  stock_valued_picking_report o a que no sabes como solucionar el problema? ¿o que no se va a migrar de momento el modulo stock_picking_taxes?

gracias.

**Comment by pedrobaeza** [comment]
A que usamos ese módulo en su lugar.

**Comment by albokasoft** [comment]
Muchas gracias.

**Comment by albokasoft** [comment]
Buenos días Pedro, he instalado el modulo pero no veo exactamente que me ha instalado. Lo que necesitaba era tener el precio de venta de cada producto en los Albaranes.

Un saludo.

**Comment by pedrobaeza** [comment]
Lee lo que ofrece el módulo y si no te vale, tendréis que adaptarlo a vuestras necesidades.
