### ISSUE TITLE
bom_component_massive_change traceback

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#157]
Al crear nuevo cambio. NO DABA ANTES de incluir el campo reason. Da desde el pasado viernes que se tocó el módulo.

Odoo

```
OpenERP Server Error

Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5723, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/v8/core/openerp/models.py", line 5623, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_bom_component_change/models/mrp_bom_change.py", line 56, in onchange_operation
    return {'domain': {'boms': [('id', 'in', bom_lst)]}}
UnboundLocalError: local variable 'bom_lst' referenced before assignment
```

**Comment by pedrobaeza** [comment]
Eso da porque no has seleccionado componente antiguo. No debería llegarse a esa condición, porque el campo debería ser requerido. Lo cambio...

**Comment by anajuaristi** [comment]
No... Pero da al pulsar el boton nuevo. Ahi aun no te ha dado tiempo a
seleccionar nada.
Despues del traceback se puede seguir y funciona

**Comment by pedrobaeza** [comment]
OK, entendido, entonces es porque el onchange se ejecuta también al principio. Lo arreglo.

**Comment by pedrobaeza** [comment]
Ya está arreglado, pero la vista está fatal. ¿Qué pintan los botones en medio? Lo suyo es que sigan aspecto v7, que son declarados en la cabecera con <header>. @Daniel-CA, este tipo de cosas a estas alturas ya no se pueden permitir así. Corrígelo.

**Comment by Daniel-CA** [comment]
No sabía que todos los botones tienen que ir en el header, al final es algo puramente estético, lo cambio.

**Comment by pedrobaeza** [comment]
Es más bien de funcionalidad, no estético. De todas formas, como principio general, los botones que actúan sobre todo el registro activo (como estos), van en header. Otros que sean sólo una sub-función, como el calcular datos de la pestaña de la orden de producción o el actualizar impuestos, sí que van situados contextualmente en el sitio donde está la parte que afecta.

**Comment by Daniel-CA** [comment]
Este issue se puede cerrar, ya esta hecho el merge.

**Comment by anajuaristi** [comment]
Verificado que se ha modificado la vista.
Off topic... queda mucho mejor ahora ;P
:+1: Cierro
