### ISSUE TITLE
[product_attribute_types]

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#200]
```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3933, in _write
    recs.recompute()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5568, in recompute
    rec1._write(values)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3792, in _write
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 2299, in _check_selection_field_value
    elif val in dict(self._columns[field].selection(self, cr, uid, context=context)):
TypeError: 'NoneType' object is not callable
```

**Comment by oihane** [comment]
He probado en local y no da este error pero tampoco entiendo a que se debe, parece como que no existiese la opción del `selection` que se le pasa pero eso no puede ser.
Tal vez se deba a algún cambio que hayan hecho en el `core`? No lo sé.

@pedrobaeza tienes alguna idea?

**Comment by oihane** [comment]
Se me ha olvidado indicar que este error da al intentar _grabar_ un nuevo `attr_type` a los atributos

**Comment by pedrobaeza** [comment]
El error se debe al campo related en _product.attribute.line_ con store=True. No se han indicado los posibles valores de ese campo con su etiqueta, y por eso da ese error. Se quita el error quitando el store=True. Tenlo en cuenta para otras veces.

Otra cosa, @oihane, hay que tener cuidado con los valores required y default para proveer mecanismos adecuados para:
- Evitar errores de usuario: un atributo no puede ser nunca de tipo vacío.
- Actualizar los datos ya existentes, a la vez que proveer un dato adecuado cuando por programación no se completa el nuevo campo. Para eso es el default.
