### ISSUE TITLE
Traceback: Al asignar un tipo al atributo y grabar

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#201]
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 516, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 279, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 732, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 375, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3933, in _write
    recs.recompute()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5568, in recompute
    rec1._write(values)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3792, in _write
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 2299, in _check_selection_field_value
    elif val in dict(self._columns[field].selection(self, cr, uid, context=context)):
TypeError: 'NoneType' object is not callable

**Comment by oihane** [comment]
DUPLICADO #200, cierro
