### ISSUE TITLE
Traceback en la instalación de quality samples

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#205]
Buenas... en un entorno donde previamente no se haya instalado quality ext, intentas instalar quality samples y da este traceback

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/v8/core/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/v8/core/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/v8/core/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/v8/core/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/v8/core/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 756, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str)
  File "/opt/odoo/v8/core/openerp/tools/convert.py", line 841, in model_id_get
    return model_data_obj.get_object_reference(cr, self.uid, mod, id_str)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/ir/ir_model.py", line 950, in get_object_reference
    return self.xmlid_lookup(cr, uid, "%s.%s" % (module, xml_id))[1:3]
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/v8/core/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/ir/ir_model.py", line 908, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: quality_control.qc_test_search_view" while parsing /opt/odoo/v8/odoomrp-wip/quality_control_samples/views/qc_test_view.xml:55, near
<record model="ir.ui.view" id="qc_test_search_view_inh_controlsamples">
            <field name="name">qc.test.search.view.inh.controlsamples</field>
            <field name="model">qc.test</field>
            <field name="inherit_id" ref="quality_control.qc_test_search_view"/>
            <field name="arch" type="xml">
                <field name="name" position="after">
                    <field name="origin"/>
                </field>
                <field name="enabled" position="after">
                    <newline/>
                    <field name="categ_id"/>
                    <field name="product_id"/>
                    <field name="picking_id"/>
                    <field name="lot_id"/>
                    <field name="production_id"/>
                </field>
                <filter string="Enabled" position="after">
                    <filter string="Category" domain="[]" context="{'group_by':'categ_id'}"/>
                    <filter string="Product" domain="[]" context="{'group_by':'product_id'}"/>
                    <filter string="Picking" domain="[]" context="{'group_by':'picking_id'}"/>
                    <filter string="Lot" domain="[]" context="{'group_by':'lot_id'}"/>
                    <filter string="Production" domain="[]" context="{'group_by':'production_id'}"/>
                </filter>
            </field>
        </record>

```

**Comment by oihane** [comment]
sin más información... no puedo verificar por que da

**Comment by pedrobaeza** [comment]
Te está diciendo que es al instalar el módulo. Prueba a instalarlo en un entorno local a ver si da.

**Comment by oihane** [comment]
Es que en local no da, y mirando el codigo está correcto...

**Comment by anajuaristi** [comment]
Me ha dado en ALM y como antes el módulo se llamaba quality_ext y la diferencia es que en wip estaba ese instalado y en alm, no.. pues he pensado que podía ser por eso. No sé.

**Comment by pedrobaeza** [comment]
Alm  no está actualizado. Hay que hacer una buena limpieza en él.

**Comment by anajuaristi** [comment]
Ok. Pero @pedrobaeza a qué te refieres? Porque ayer estuve allí y creo que a primera hora @oihane actualizó el entorno.

**Comment by pedrobaeza** [comment]
Si tiene el quality_control_ext pululando no está actualizado. De todas formas, como hemos renombrado módulos, hay que purgarlos como ha pasado con el entorno demo.

**Comment by oihane** [comment]
Algo raro ha habido ya que se habían quedado carpetas pilladas. Yo en alm, instalé sin querer, a la primera.

**Comment by oihane** [comment]
Parece que fue un error puntual, ya que en todas cuando he probado a instalar en nuevas db, ha funcionado.
Cierro issue
