### ISSUE TITLE
TRACEBACK self.default_code NULO en repair_analytics

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#397]
```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 959, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/v8/core/openerp/http.py", line 1045, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/v8/core/openerp/http.py", line 816, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/v8/core/openerp/http.py", line 100, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/v8/core/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3478, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/v8/core/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/v8/core/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/v8/core/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/v8/core/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_repair_analytic/models/mrp_repair.py", line 36, in action_repair_end
    line, factor)
  File "/opt/odoo/v8/odoomrp-wip/mrp_repair_analytic/models/mrp_repair.py", line 48, in _catch_repair_line_information_for_analytic
    name += ' - ' + self.default_code
ValueError: "'mrp.repair' object has no attribute 'default_code'" while evaluating
u'action_repair_end()'
```

**Comment by anajuaristi** [comment]
Arreglado el error del self.default_code pero... detecto un par de pequeñas cosillas en este módulo:
1. el diario en que se imputan las líneas de material de la reparación debe ser "materiales" y no timesheet
2. Las líneas se están creando con la parametrización 100%facturable, y deberían ser "no facturables", es decir, con el campo en blanco. 
3. Si la cantidad de línea en la reparación es >1, no está multiplicando el importe de la línea analítica, asigna el coste unitario del producto, sin tener en cuenta la cantidad registrada.
4. Está creando las cantidades en positivo, o sea, como ingresos. Son costes, por lo que los importes entiendo que deberían imputarse en negativo

El resto estaría correcto a simple vista, a falta de más pruebas.

**Comment by agaldona** [comment]
El módulo es de @alfredoavanzosc creo que es más recomendable que lo mire el, si yo me "libro" antes de que lo haya podido mirar el, ya me pondré con esto.

**Comment by pedrobaeza** [comment]
Esto ya no aplica con la nueva versión del módulo.

**Comment by anajuaristi** [comment]
¿Hay una nueva versión del repair_analytics?

**Comment by pedrobaeza** [comment]
Perdona, he mirado mal el título y creía que era del código de las variantes. Reabro...

**Comment by alfredoavanzosc** [comment]
Hola buenas, tengo hechos todos los puntos que solicita Ana, excepto el primero. ¿Alguien me puede decir  por favor como debo de coger el diario de materiales?, gracias.

**Comment by pedrobaeza** [comment]
El diario de materiales se define en el módulo de estimación de costes, y se puede obtener el id con la referencia al XML-ID.

**Comment by alfredoavanzosc** [comment]
Entendido, entonces al módulo "mrp_repair", le meto la dependencia del módulo de estimación de costes. Gracias.

**Comment by anajuaristi** [comment]
:+1: Si. Aparte de que los métodos y demás que debería utilizar reparaciones para crear las líneas analíticas, se podrían perfectamente coger de ese módulo... pero... 

@pedrobaeza ... me surge una duda. En la reparación como tal no existen costes "estimados" y "reales" con lo cual, el valor del importe... ¿deberia ir tanto a los campos en analítica que reflejan costes estimados, como al que refleja el coste real?
¿O dejamos los estimados a cero y reflejamos sólo en el coste real? Así creo que lo tenemos ahora. 
Lo digo por mantener la consistencia con respecto a los datos que reflejarán las OFs y también por si acaso una reparación imputa costes al mismo proyecto que otras OFs.
En principio, entiendo que sería correcto suponer que una reparación es un coste real y no previsto con anterioridad... no? En caso de que no sea así... ¿Podriamos hacer por ejemplo que al confirmar la reparación se imputen en los campos de estimados y al finalizar la reparación, el coste real... pero no sé si merece la pena en este caso. Igual lo estoy complicando. 
¿que opinas?

**Comment by pedrobaeza** [comment]
Creo recordar que en las reparaciones estándar tú das un presupuesto, y luego haces la reparación y pasas factura, con lo que puede haber una diferencia entre lo presupuestado y lo real. Eso se podría reflejar en estimados y reales.

**Comment by alfredoavanzosc** [comment]
Solicitado el PR https://github.com/odoomrp/odoomrp-wip/pull/572

**Comment by anajuaristi** [comment]
Merge realizado. Cierro
