### ISSUE TITLE
[Quality_control] Traceback when I choose a template in a test.

### ISSUE THREAD

**Issue by gaultp** [odoomrp/odoomrp-wip#398]
Scenario:
In Quality control menu, I create a test and select a template already created.
Here is the traceback coming then:

```
Traceback (most recent call last):
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/home/pgault/openerp/8.0/demo/git/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/pgault/openerp/8.0/demo/git/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoomrp-wip/quality_control/wizard/qc_test_wizard.py", line 62, in action_create_test
    context=context)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoomrp-wip/quality_control/models/quality_control.py", line 498, in set_test_template
    context)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/addons/mail/mail_thread.py", line 427, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 359, in old_api
    recs = self.browse(cr, uid, ids, context)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/models.py", line 5139, in browse
    ids = _normalize_ids(arg)
  File "/home/pgault/openerp/8.0/demo/git/odoo/openerp/models.py", line 5979, in _normalize_ids
    return tuple(arg)
TypeError: 'builtin_function_or_method' object is not iterable
```

**Comment by anajuaristi** [comment]
Hi @gaultp 

Could you write step by step the actions to obtain the error. I could not reproduce on our environment. 
Thank you!!

**Comment by gaultp** [comment]
OK. I installed module quality_control_tolerance. I created a test template in Quality Control/Configuration/Test Template.
![test template odoo](https://cloud.githubusercontent.com/assets/7704085/5266663/1d2a8e38-7a19-11e4-8aca-331dfb8410ec.png)

Then I go to create a test.
First problem, when I add a Line, just few fields are editable.
![test odoo](https://cloud.githubusercontent.com/assets/7704085/5266767/dcb09f40-7a19-11e4-8077-46c66ff68b20.png)

So I think about using a template. When I select and accept the template in the wizard, I get this error:
![test error](https://cloud.githubusercontent.com/assets/7704085/5266788/09f342b4-7a1a-11e4-9159-125e9bc6d14a.png)

**Comment by pedrobaeza** [comment]
I'm refactoring full quality set of modules, so you will need to uninstall current set, install the new, and try again. I let you know when I have it.

**Comment by pedrobaeza** [comment]
As this is totally changed, this issue doesn't apply now.
