### ISSUE TITLE
mrp_packaging traceback

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#420]
Entorno de la ofi, bbdd ALM
OF 134

Al pulsar el botón de crear envasados, da este traceback

```
Traceback (most recent call last):
  File "/opt/odoo/server-v8/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server-v8/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server-v8/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server-v8/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server-v8/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server-v8/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server-v8/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 391, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons_OdooMRP/odoomrp-wip/mrp_packaging/models/mrp_production.py", line 60, in create_mo_from_packaging_operation
    new_op = self.create(data['value'])
  File "/opt/odoo/server-v8/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/server-v8/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 3999, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/server-v8/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 4184, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/server-v8/openerp/osv/fields.py", line 740, in set
    if act[0] == 0:
KeyError: 0
```

**Comment by anajuaristi** [comment]
arreglado en #426 cierro
