### ISSUE TITLE
Error al instalar 'quality_control'

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#446]
```
Traceback (most recent call last):
  File "/opt/odoo/server-v8/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server-v8/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server-v8/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server-v8/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server-v8/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server-v8/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server-v8/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/server-v8/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/server-v8/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/server-v8/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/server-v8/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/odoo/server-v8/openerp/modules/module.py", line 283, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 2622, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 2395, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/opt/odoo/server-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/fields.py", line 363, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/opt/odoo/server-v8/openerp/fields.py", line 1487, in convert_to_write
    return value.id
AttributeError: 'int' object has no attribute 'id'
```

Además de darlo al hacer un update all lo da al instalar

**Comment by pedrobaeza** [comment]
Parecen secuelas de los antiguos módulos. De todas formas, prueba a no utilizar el botón instalación inmediata para que el log sea más claro y dime en cuál de los módulos es. El problema está pasando al asignar un valor por defecto. Sólo veo como posible problema esta línea, por no ser un integer directamente, pero no creo: https://github.com/odoomrp/odoomrp-wip/blob/8.0/quality_control/models/qc_test.py#L69

**Comment by anajuaristi** [comment]
Cierro esto. Ya hemos instalado quality control en todos los entornos
