### ISSUE TITLE
[ERROR] Relacionado con <stock_quant_manual_assign>

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#450]
No es que sea bloqueante pero me sale este error de vez en cuando en el log

```
2014-12-16 10:37:12,989 8265 ERROR odoo_almetac openerp.sql_db: bad query: delete from assign_manual_quants where id IN (1)
Traceback (most recent call last):
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "assign_wizard" violates not-null constraint
CONTEXTO:  SQL statement "UPDATE ONLY "public"."assign_manual_quants_lines" SET "assign_wizard" = NULL WHERE $1 OPERATOR(pg_catalog.=) "assign_wizard""

2014-12-16 10:37:13,042 8265 ERROR odoo_almetac openerp.addons.base.ir.ir_cron: Call of self.pool.get('osv_memory.autovacuum').power_on(cr, uid, *()) failed in Job 1
Traceback (most recent call last):
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/addons/base/ir/osv_memory_autovacuum.py", line 31, in power_on
    model._transient_vacuum(cr, uid, force=True)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/models.py", line 4977, in _transient_vacuum
    self._transient_clean_rows_older_than(cr, self._transient_max_hours * 60 * 60)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/models.py", line 4941, in _transient_clean_rows_older_than
    self.unlink(cr, SUPERUSER_ID, ids)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/models.py", line 3543, in unlink
    'where id IN %s', (sub_ids,))
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "assign_wizard" violates not-null constraint
CONTEXTO:  SQL statement "UPDATE ONLY "public"."assign_manual_quants_lines" SET "assign_wizard" = NULL WHERE $1 OPERATOR(pg_catalog.=) "assign_wizard""
```

**Comment by pedrobaeza** [comment]
Eso es porque en el asistente no se puso ondelete="cascade". @mikelarre, ponlo por favor.
