### ISSUE TITLE
[quality control] add test item, rase error report float divison by zero

### ISSUE THREAD

**Issue by jeffery9** [odoomrp/odoomrp-wip#462]
to reproduce this error.  create a test and add test item.

when click add an item, it raise the error.

becuase can not upload the picture, attached the log

```
            Traceback (most recent call last):
              File "/opt/odoo/openerp/http.py", line 517, in _handle_exception
                return super(JsonRequest, self)._handle_exception(exception)
              File "/opt/odoo/openerp/http.py", line 538, in dispatch
                result = self._call_function(**self.params)
              File "/opt/odoo/openerp/http.py", line 294, in _call_function
                return checked_call(self.db, *args, **kwargs)
              File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
                return f(dbname, *args, **kwargs)
              File "/opt/odoo/openerp/http.py", line 291, in checked_call
                return self.endpoint(*a, **kw)
              File "/opt/odoo/openerp/http.py", line 754, in __call__
                return self.method(*args, **kw)
              File "/opt/odoo/openerp/http.py", line 387, in response_wrap
                response = f(*args, **kw)
              File "/opt/odoo/addons/web/controllers/main.py", line 949, in call_kw
                return self._call_kw(model, method, args, kwargs)
              File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
                return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
              File "/opt/odoo/openerp/api.py", line 237, in wrapper
                return old_api(self, *args, **kwargs)
              File "/opt/odoo/openerp/api.py", line 360, in old_api
                result = method(recs, *args, **kwargs)
              File "/opt/odoo/openerp/models.py", line 5760, in onchange
                record._onchange_eval(name, field_onchange[name], result)
              File "/opt/odoo/openerp/models.py", line 5660, in _onchange_eval
                method_res = method(self)
              File "/opt/odoo/addons/quality_control_tolerance/models/qc_test.py", line 32, in onchange_tolerance_above
                self.max_value / self.max_value)
            ZeroDivisionError: float division by zero
```

**Comment by jeffery9** [comment]
the issue is caused by quality_control_tolerance

**Comment by pedrobaeza** [comment]
Yeah, quality_control_tolerance is still a WIP. Sorry for not informing correctly. I will work on it today.

**Comment by jeffery9** [comment]
is there have any documents about how to use quality control.
thanks,

On Fri, Dec 19, 2014 at 8:52 PM, Pedro M. Baeza notifications@github.com
wrote:

> Yeah, quality_control_tolerance is still a WIP. Sorry for not informing
> correctly. I will work on it today.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/462#issuecomment-67634439.

## 

Jeffery        -kunshan

**Comment by pedrobaeza** [comment]
No, sorry, but I can give you some hints:
- Define a test with its questions and answers.
- If you install stock or production, you will have some "triggers" at produc category, product or variant level to define on each picking type or at the end of the production.
- If you define one of these triggers to be attached to one test, when the move is done, a QC inspection is automatically created, and then you can fill it to know if it's correct or not.

Regards.

**Comment by jeffery9** [comment]
we want to print inspection to fill the test data, when should you create the pdf report, thanks.

**Comment by pedrobaeza** [comment]
I have push the completed quality_control_tolerance, so now you can fully use it without issues.

About printing a quality inspection report, for now is not on our scope, but if you want, you can contribute with this addition.

Thanks for the reporting.

Regards.
