### ISSUE TITLE
[quality_control] Error

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#463]
Reportado por un cliente:

Cuando llegamos a la Etapa FABRICAR aparece esto en pantalla y no podemos seguir.

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mrp/wizard/mrp_product_produce.py", line 123, in do_produce
    data.product_qty, data.mode, data, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/quality_control_mrp/models/mrp_production.py", line 39, in action_produce
    production_id, production_qty, production_mode, wiz=wiz)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/quality_control_mrp/models/mrp_production.py", line 57, in action_produce
    inspection_model._make_inspection(move, test)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/quality_control/models/qc_inspection.py", line 159, in _make_inspection
    object_ref, test))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/quality_control/models/qc_inspection.py", line 86, in create
    return super(QcInspection, self).create(vals)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3994, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4179, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/v8/core/openerp/osv/fields.py", line 1379, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 276, in _set_followers
    self.message_subscribe(cr, uid, [id], list(new-old), context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 1733, in message_subscribe
    }, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_followers.py", line 56, in create
    res = super(mail_followers, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3994, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4198, in _create
    recs.recompute()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5597, in recompute
    f.name: rec[f.name] for f in field.computed_fields
  File "/opt/odoo/v8/core/openerp/models.py", line 5597, in <dictcomp>
    f.name: rec[f.name] for f in field.computed_fields
  File "/opt/odoo/v8/core/openerp/models.py", line 5486, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/v8/core/openerp/fields.py", line 771, in __get__
    self.determine_value(record)
  File "/opt/odoo/v8/core/openerp/fields.py", line 849, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/v8/core/openerp/fields.py", line 829, in compute_value
    self._compute_value(records)
  File "/opt/odoo/v8/core/openerp/fields.py", line 821, in _compute_value
    self.compute(records)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/v8/odoomrp-wip/quality_control_stock/models/qc_inspection.py", line 31, in get_lot
    self.lot = self.object_id.lots_id[0]
AttributeError: 'stock.move' object has no attribute 'lots_id'
```

**Comment by oihane** [comment]
`stock.move` tiene un campo llamado `lot_ids`

**Comment by pedrobaeza** [comment]
Ha sido un error de typo.
