### ISSUE TITLE
[8.0] mrp_manufacturing_order_sale_line

### ISSUE THREAD

**Issue by ccarly** [odoomrp/odoomrp-wip#465]
Al filtrar las ordenes de producción por clientes emite error en el campo partner

```
Traceback (most recent call last):
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/home/openerp/bin/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/bin/8.0/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/openerp/bin/8.0/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 2100, in read_group
    assert groupby_def and groupby_def._classic_write, "Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True"
AssertionError: Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True
```

**Comment by ccarly** [comment]
Solución:

```
mrp_manufacturing_order_sale_line/models/mrp_production.py
25c25
<                               related='sale_line.order_id.partner_id')
---
>                               related='sale_line.order_id.partner_id', store=True)
```

**Comment by pedrobaeza** [comment]
Ya lo he solucionado en https://github.com/odoomrp/odoomrp-wip/commit/64254589b6c253ae0d740cf80797c2337a19c85c.

Gracias por avisar.

Un saludo.
