### ISSUE TITLE
mrp_manufacturing_order_sale_line

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#470]
Da este traceback al entrar en ordenes de fabricación

Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/opt/odoo/v8/core/openerp/http.py", line 856, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5061, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3078, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3222, in _read_from_database
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column mrp_production.partner does not exist
LINE 1: ...duction."product_qty",mrp_production."routing_id",mrp_produc...

Antes no daba. Viene del merge que se hizo el 17 de oct.
Asigno a Dani. De momento, desinstalo módulo

**Comment by pedrobaeza** [comment]
Arreglado, no hace falta nada más.
