### ISSUE TITLE
Short dump when confirming a manufacturing order

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#506]
Odoo Server Error

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 960, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/v8/core/openerp/http.py", line 1057, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/v8/core/openerp/http.py", line 828, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/v8/core/openerp/http.py", line 108, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/v8/core/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3478, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/v8/core/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/v8/core/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/v8/core/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/v8/core/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/v8/core/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 28, in action_confirm
    res = super(MrpProduction, self).action_confirm()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_project_link/models/mrp_production.py", line 71, in action_confirm
    result = super(MrpProduction, self).action_confirm()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 395, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/v8/odoomrp-wip/mrp_subcontracting/models/mrp_production.py", line 64, in action_confirm
    res = super(MrpProduction, self).action_confirm()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_lot_reserve/models/mrp_production.py", line 63, in action_confirm
    res = super(MrpProduction, self).action_confirm()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mrp/mrp.py", line 1181, in action_confirm
    self._make_production_produce_line(cr, uid, production, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_product_variants/models/mrp_production.py", line 189, in _make_production_produce_line
    'attribute_value_ids': [(6, 0, att_values_ids)]})
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/product_variant_default_code/models/product.py", line 126, in create
    product = super(ProductProduct, self).create(values)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/product/product.py", line 1134, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3994, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4050, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/product_variant_default_code/models/product.py", line 106, in create
    return super(ProductTemplate, self).create(vals)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/product/product.py", line 709, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3994, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4132, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (136, null, null, 1.0, null, null, null, 1, fixed, 1, null, 2015-01-04 13:36:30.744055, 1.0, 1, f, null, null, 1, null, 1, consu, null, null, null, 2015-01-04 13:36:30.744055, t, 1, t, null, null, null, null, null, null, f, 7, f, f, null, f, 1, t, f, f, empty, null, null, null, null, null, f, null, null, null, null, null, no-message, no-message, null, 1.0, null).
" while evaluating
u'action_confirm()'
```

**Comment by pedrobaeza** [comment]
@oihane, parece una cuestión de variantes. Podrías revisarlo?

**Comment by oihane** [comment]
Pues algo raro hay, ya que se esta creando un ProductTemplate, y eso el de variantes no lo hace, ya que se basa en que existe el Template.
Y no sé como reproducir el error que se reporta aquí.

@ybofr could you please extend the issue? Tell us which product.template were you using, or which MO is the one giving this error. I was not able to replicate the error. Thanks in advance

**Comment by anajuaristi** [comment]
@ybofr We were not able reproducing the error.
Could you please extend a little bit the information about the product/template or MO number where you obtained the error so we could reproduce and fix it?

If we can not reproduce, we can not solve so maybe could be a punctual issue solved by now. 

Please, let us know.

Thank you:
Ana

**Comment by anajuaristi** [comment]
We noticed that a similar error is produced when you try to confirm an order with product_id null, this is, the product to produce has not been assigned. 

We have just added a warning to advice of this circunstance. If you can reproduce again, please reopen.
I close the issue.
