### ISSUE TITLE
Noviembre 2 destroyed somehow

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#512]
Hi,

I cannot test on Noviembre2. Whatever I do I receive short dumps. For instance, I wanted to test something in the BOM and here is what I got.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_bom_catch_product_code/models/mrp_bom.py", line 28, in create
    bom.code = bom.product_tmpl_id.default_prefix
AttributeError: 'product.template' object has no attribute 'default_prefix'

**Comment by anajuaristi** [comment]
Hi. We just updated environment with a lot of merges so, it could be that we introduced new tracebacks  if some dependencies are not correctly set, or maybe you tried before we restart server. 
On this case I could not reproduce the error you are reporting so maybe is solved with server restart

**Comment by ybofr** [comment]
ok. I will close the issue
