### ISSUE TITLE
Short dump when duplicating a BOM

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#517]
I'm trying to duplicate my poudre of perlimpinpin in Noiembre2.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 391, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 395, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/v8/odoomrp-wip/mrp_bom_version/models/mrp.py", line 60, in copy
    return super(MrpBom, self).copy(default=default)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 507, in new_api
    result = [method(self._model, cr, uid, id, _args, *_kwargs) for id in self.ids]
  File "/opt/odoo/v8/core/openerp/models.py", line 4755, in copy
    new_id = self.create(cr, uid, data, context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_bom_catch_product_code/models/mrp_bom.py", line 28, in create
    bom.code = bom.product_tmpl_id.default_prefix
AttributeError: 'product.template' object has no attribute 'default_prefix'

**Comment by anajuaristi** [comment]
This is caused due to an enhancement on product_default_code module. 
The field default_prefix, has been changed by reference_mask so mrp_bom_catch_product_code must be modified in consecuence.

By the moment I will desinstall mrp_bom_catch_product_code from environment in order to avoid the traceback until module it's upgraded adapted to this new change.

**Comment by anajuaristi** [comment]
@alfredoavanzosc @pedrobaeza 
La modificación en product_default_code donde ahora ya no se incluye solo el prefijo para la creación del código de variantes, sino una máscara para el formateo del campo código, impacta en el módulo mrp_bom_catch_product_code, que usaba el campo antiguo para "nombrar" los boms.

Ya direis cómo lo dejamos porque en principio, no podemos asignar la máscara al nombre del bom, quedaría un poco raro.

**Comment by pedrobaeza** [comment]
Hay que resolver la máscara y ponerla al BoM.

**Comment by anajuaristi** [comment]
Quizás haya que ir por la calle de en medio y solo actualizar la referencia en el bom si se trata de un bom con producto específico al que se le haya puesto un valor en default code, sin más.

**Comment by pedrobaeza** [comment]
Vale, se puede ver esa alternativa. @alfredoavanzosc, échale por favor un vistazo.

**Comment by alfredoavanzosc** [comment]
Realizado, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/541
