### ISSUE TITLE
Traceback sale_order_taxes entorno demo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#548]
Meter un pedido y al pulsar actualizar impuestos con el módulo sale_order_taxes instalado sale este traceback

Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/v8/odoomrp-wip/sale_order_taxes/models/sale_order.py", line 100, in button_dummy
    self._calc_taxes()
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/odoomrp-wip/sale_order_taxes/models/sale_order.py", line 83, in _calc_taxes
    for tax in self.compute(order).values():
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/v8/odoomrp-wip/sale_order_taxes/models/sale_order.py", line 71, in compute
    tax_grouped[key]['base_amount'] += val['base_amount']
KeyError: 'base_amount'

**Comment by oihane** [comment]
Corregido en #553 y mergeado, cierro issue
