### ISSUE TITLE
TRACEBACK

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#61]
```
Traceback (most recent call last):
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 479, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 498, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 314, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 311, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 688, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 363, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoomrp/odoo/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoomrp/odoo/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 357, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/models.py", line 5679, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoomrp/odoo/openerp/models.py", line 5613, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoomrp/temp_addons/warning_log/models/warning.py", line 122, in product_id_change_with_wh
    vals = super(SaleOrderLine, self).product_id_change_with_wh(
NameError: global name 'saleOrderLine' is not defined
```

**Comment by oihane** [comment]
PR #13
