### ISSUE TITLE
Sale_order_type Error al instalar

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#692]
Hola.

He obtenido el siguiente error al tratar de instalar el módulo:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 562, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 299, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 791, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 395, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 755, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/base/ir/ir_model.py", line 934, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/base/ir/ir_model.py", line 924, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: account.sales_journal" while parsing /opt/odoo/odoo_8_mrp/src/linked-addons/sale_order_type/data/default_type.xml:4, near
```

![image](https://cloud.githubusercontent.com/assets/8233008/6440676/c642c384-c0df-11e4-8ee5-050bd4033206.png)

¿Podría sobrarle una "s" a "account.sales_journal? No se si será fallo de nuestra instalación.

**Comment by pedrobaeza** [comment]
Buenas, Eduardo, creo que se debe a una instalación no actualizada. ¿Puedes revisar a ver?

**Comment by ghost** [comment]
La instalación del módulo es del día 16 de febrero, hace 14 días, y el módulo no se actualiza en Github desde hace 1 mes. Si te refieres a la instalación inicial de Odoo, ésta es de principios de enero si no recuerdo mal. Quizá esté ahí el problema.

El jueves-viernes tenemos programado hacer otro pull, así que miraremos de actualizar todo y revisamos este módulo.

**Comment by pedrobaeza** [comment]
Me refiero a la de Odoo. Luego me cuentas.

**Comment by oihane** [comment]
Por lo que he visto el `sales_journal` está aquí:
https://github.com/odoo/odoo/blob/8.0/addons/account/demo/account_minimal.xml#L311

Que se encuentra en los datos demo.

**Comment by oihane** [comment]
Buscando en odoo he descubierto que los diarios se crean aquí:
https://github.com/odoo/odoo/blob/8.0/addons/account/account.py#L3141
