### ISSUE TITLE
Error en mrp_stock_location_route_fix

### ISSUE THREAD

**Issue by juanfe** [odoomrp/odoomrp-wip#726]
Hola, encontré un error en el módulo mrp_stock_location_route_fix, al ingresar registros en stock.warehouse, el error es:

Traceback (most recent call last):
  File "/opt/odootest/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odootest/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odootest/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odootest/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odootest/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odootest/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odootest/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odootest/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odootest/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odootest/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odootest/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odootest/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odootest/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odootest/odoo/openerp/tools/convert.py", line 899, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/opt/odootest/odoo/openerp/tools/yaml_import.py", line 958, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/opt/odootest/odoo/openerp/tools/yaml_import.py", line 894, in process
    self._process_node(node)
  File "/opt/odootest/odoo/openerp/tools/yaml_import.py", line 905, in _process_node
    self.process_record(node)
  File "/opt/odootest/odoo/openerp/tools/yaml_import.py", line 331, in process_record
    self.module, record_dict, record.id, noupdate=self.isnoupdate(record), mode=self.mode, context=context)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/addons/stock/stock.py", line 3422, in create
    new_objects_dict = self.create_routes(cr, uid, new_id, warehouse, context=context)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/addons/mrp/stock.py", line 275, in create_routes
    manufacture_pull_vals = self._get_manufacture_pull_rule(cr, uid, warehouse, context=context)
  File "/opt/odootest/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odootest/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odootest/odoo/addonsmrp-wip/mrp_stock_location_route_fix/models/stock_warehouse.py", line 28, in _get_manufacture_pull_rule
    lang='en_US')._get_manufacture_pull_rule(warehouse)
  File "/opt/odootest/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
.
.
.
  File "/opt/odootest/odoo/addonsmrp-wip/mrp_stock_location_route_fix/models/stock_warehouse.py", line 28, in _get_manufacture_pull_rule
    lang='en_US')._get_manufacture_pull_rule(warehouse)
  File "/opt/odootest/odoo/openerp/models.py", line 5286, in with_context
    return self.with_env(self.env(context=context))
  File "/opt/odootest/odoo/openerp/api.py", line 733, in __call__
    return Environment(cr, uid, context)
  File "/opt/odootest/odoo/openerp/api.py", line 703, in **new**
    for env in envs:
  File "/opt/odootest/odoo/openerp/api.py", line 921, in **iter**
    return iter(self.envs)
RuntimeError: maximum recursion depth exceeded while calling a Python object 

Se queda en un loop.

Yo lo resolví, comentando las líneas del método _get_manufacture_pull_rule, pero también se puede retirar ese modelo, y debe funcionar bien.

Cordialmente

Juan Fernando Jaramillo Botero

**Comment by pedrobaeza** [comment]
Buenas, Juan,

Eso es porque tienes una versión antigua del mismo. Está reparado en https://github.com/odoomrp/odoomrp-wip/commit/d842b91253ae9dc7f4c928b68f8bfd90c5437712

De todas formas, actualiza Odoo, porque ya no hace falta este módulo.

Un saludo.
