### ISSUE TITLE
mrp_operations_extension: Dependencia con "hr"

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#753]
Hola.

Si intento añadir un Usuario en la pestaña Operadores de un Centro de producción, sin tener instalado el módulo de Recursos Humanos, me da el siguiente error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo_8_mrp/src/linked-addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/models.py", line 5855, in onchange
    newval = record[name]
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/models.py", line 5557, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/fields.py", line 768, in __get__
    self.determine_draft_value(record)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/fields.py", line 876, in determine_draft_value
    self._compute_value(record)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/fields.py", line 815, in _compute_value
    self.compute(records)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_mrp/src/OCA/OCB/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo_8_mrp/src/other/odoomrp/odoomrp-wip/mrp_operations_extension/models/mrp_workcenter.py", line 32, in _operators_number_avg_cost
    op_avg_cost += operator.employee_ids[0].product_id.standard_price
AttributeError: 'res.users' object has no attribute 'employee_ids'
```

Supongo que faltaría o añadir una dependencia al módulo "hr_timesheet" o capturar el error.

**Comment by anajuaristi** [comment]
Correcto.
El coste de operador está en el correspondiente producto de la ficha de empleado y por tanto la dependencia es requerida.
Gracias por reportarlo!!

**Comment by anajuaristi** [comment]
@agaldona para tenerlo en cuenta cuando revisemos el módulo de costes.

**Comment by pedrobaeza** [comment]
Ya la he añadido yo. Gracias por reportarlo.
