### ISSUE TITLE
Traceback al abrir números de serie/lote en demo.odoomrp.com

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#79]
```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 495, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 685, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 360, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 345, in fields_view_get
    res = super(mail_thread, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/v8/core/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 1556, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/odoo/v8/core/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/ir/ir_ui_view.py", line 847, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/opt/odoo/v8/core/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/addons/base/ir/ir_ui_view.py", line 381, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `remark` does not exist

Error context:
View `stock.production.lot.form`
[view_id: 714, xml_id: stock.view_production_lot_form, model: stock.production.lot, parent_id: n/a]
```

**Comment by oihane** [comment]
lo de remark es de un modulo antiguo, @anajuaristi vuelva a probar, pero he accedido yo y ya no lo daba.
Si en algún otro entorno te encuentras con el mismo error busca en los módulos instalados si hay alguno con "remark" en el nombre y desinstalalo ya que ahora no existen
