### ISSUE TITLE
Traceback al confirmar pedido de compra

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#80]
Servidor de la ofi.

```
OpenERP Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 496, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 513, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 279, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 276, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 723, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 372, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoomrp/odoo/addons/web/controllers/main.py", line 952, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 1026, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 797, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/odoomrp/odoo/openerp/http.py", line 96, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/odoomrp/odoo/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/models.py", line 3483, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 272, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/odoomrp/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/odoomrp/odoo/openerp/tools/safe_eval.py", line 312, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 233, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 550, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoomrp/odoo/addons/purchase/purchase.py", line 826, in action_picking_create
    picking_id = self.pool.get('stock.picking').create(cr, uid, picking_vals, context=context)
  File "/opt/odoo/odoomrp/odoo/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoomrp/temp_addons/sale_documents_comments/models/stock.py", line 61, in create
    values['sale_comment'] = (partner.picking_comment + '\n' +
ValueError: "unsupported operand type(s) for +: 'bool' and 'str'" while evaluating
u'action_picking_create()'
```

**Comment by oihane** [comment]
@anajuaristi ya no da el traceback (comprobado)
