### ISSUE TITLE
Claim: Recalcular precios en pedidos y presupuestos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#81]
En demo.odoomrp.com en pedidos de venta hay un botón "recalcular" que se supone recalcula los precios del pedido si a mitad de estarlo haciendo, se cambia la tarifa, actualizando todos los precios en función de dicha tarifa. 
Al pulsar el botón da el traceback que copypasteo.

Aparte... no tengo nombre del módulo y no sé si hay PR porque el claim es muy antiguo, de los primeros que se abrió. Apuntar aquí qué módulo es.

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 495, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 685, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 360, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 945, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/sale_order_recalculate_prices/models/sale_order.py", line 40, in recalculate_prices
    line.write(res['value'], context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 232, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: write() got an unexpected keyword argument 'context'
```

**Comment by oihane** [comment]
Pues el nombre del modulo es sale_order_recalculate_prices

**Comment by oihane** [comment]
@CsanchezC parece que el problema viene de que le pasas el context y como estas usando el nuevo API no es necesario. 
Si sustituyes en la linea 40 del fichero `sale_order_recalculate_prices/models/sale_order.py` `line.write(res['value'], context=context)` por `line.write(res['value'])` creo que ya lo tienes solucionado
