### ISSUE TITLE
Issues nueva versión "plan"

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#824]
1. Al crear abastecimientos desde "crear ventas", se crean sin regla asociada
2. Al pulsar el botón "ejecutar" abastecimiento, da un traceback max recursion... 

```
  File "/opt/odoo/server-v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/addons/base/res/res_users.py", line 300, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/odoo/server-v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 3128, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/server-v8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 3146, in read
    self.check_access_rights('read')
  File "/opt/odoo/server-v8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/api.py", line 441, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/models.py", line 3480, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/odoo/server-v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/opt/odoo/server-v8/openerp/tools/cache.py", line 117, in lookup
    r = d[key]
  File "/opt/odoo/server-v8/openerp/tools/func.py", line 66, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/server-v8/openerp/tools/lru.py", line 38, in __getitem__
    self[a[0]] = a[1]
  File "/opt/odoo/server-v8/openerp/tools/func.py", line 68, in wrapper
    lock.release()
RuntimeError: maximum recursion depth exceeded
```

**Comment by alfredoavanzosc** [comment]
Solucionados estos 2 BUGs en la última subida. https://github.com/odoomrp/odoomrp-wip/pull/799

**Comment by anajuaristi** [comment]
Al importar desde una venta da este traceback

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/other-addons/procurement_plan/wizard/wiz_load_sale_from_plan.py", line 101, in load_sales
    procurement_obj.onchange_product_id(product)['value'])
KeyError: 'value'

```

**Comment by alfredoavanzosc** [comment]
Ana... estoy ya esta hecho, lo puedes probar.

**Comment by anajuaristi** [comment]
Esto está arreglado, cierro
