### ISSUE TITLE
Error en instalación del modulo <sale_taxes_breakdown

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#83]
Relacionado con #62 

```
OpenERP Server Error
Traceback (most recent call last):
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 496, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 513, in dispatch
    result = self._call_function(**self.params)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 279, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 276, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 729, in __call__
    return self.method(*args, **kw)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/http.py", line 372, in response_wrap
    response = f(*args, **kw)
  File "/home/avanzosc2/Odoo/odoo-v8/addons/web/controllers/main.py", line 945, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/avanzosc2/Odoo/odoo-v8/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/modules/module.py", line 275, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/api.py", line 235, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/models.py", line 2486, in _auto_init
    cr.execute('SELECT min(id) FROM "%s"' % (self._table,))
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/avanzosc2/Odoo/odoo-v8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "id" does not exist
LÍNEA 1: SELECT min(id) FROM "sale_order_tax"
                    ^
```

El codigo es:

```
class SaleOrderTax(models.Model):
    _name = 'sale.order.tax'

    sale_id = fields.Many2one('sale.order', string='Sale Order',
                              ondelete='cascade')
    tax_id = fields.Many2one('account.tax', string='Tax')
    untaxed_amount = fields.Float(string='Untaxed Amount',
                                  digits_compute=
                                  dp.get_precision('Sale Price'))
    taxation_amount = fields.Float(string='Taxation',
                                   digits_compute=
                                   dp.get_precision('Sale Price'))
    total_amount = fields.Float(string='Total',
                                digits_compute=
                                dp.get_precision('Sale Price'))
```

@pedrobaeza puedes indicarme si me he colado en algo al pasarlo a la nueva API

**Comment by pedrobaeza** [comment]
No, en principio lo veo correcto. Pero esa versión no la tienes subida al PR. Por cierto, mejor llamarlo _order_id_, o según la nueva nomenclatura que hablamos, simplemente _sale_order_.

**Comment by oihane** [comment]
Al final parece que en algún momento había creado la tabla sale_order_tax y venia de ahí el problema
