### ISSUE TITLE
[8.0.1] sale_order_recalculate_prices_variants

### ISSUE THREAD

**Issue by apesquero** [odoomrp/odoomrp-wip#861]
Hola, este módulo junto con sale_product_variants_types da el siguiente error al recalcular la tarifa.

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 573, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 306, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 802, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 402, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/sale_order_recalculate_prices_variants/models/sale.py", line 31, in recalculate_prices
    super(SaleOrder, self).recalculate_prices()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/sale_order_recalculate_prices/models/sale_order.py", line 40, in recalculate_prices
    line.write(res['value'])
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_quote/models/order.py", line 123, in write
    return super(sale_order_line, self).write(cr, uid, ids, values, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3774, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3917, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 809, in set
    if act[0] == 0:
KeyError: 0

**Comment by anajuaristi** [comment]
@oihane se reproduce en demo bbdd marzo.
Pasos:
Creas un presupuesto
Cambias la tarifa
Pulsas recalcular

**Comment by oihane** [comment]
En runbot no da ningun error, cierro
