### ISSUE TITLE
[8.0.1] product_variant_cost

### ISSUE THREAD

**Issue by apesquero** [odoomrp/odoomrp-wip#870]
Hola, creo que el módulo product_variant_cost crea un conflicto con el módulo sale_product_variants_types:

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 937, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5864, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5745, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/sale_product_variants/models/sale_order.py", line 136, in onchange_product_template
    self.order_id.partner_id.id)[self.order_id.pricelist_id.id]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/product_variants_no_automatic_creation/models/pricelist.py", line 165, in template_price_get
    partner=partner).items())
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/product_variants_no_automatic_creation/models/pricelist.py", line 171, in template_price_rule_get
    products_by_qty_by_partner=[(product, qty, partner)])
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/product/pricelist.py", line 188, in price_rule_get_multi
    subres = self._price_rule_get_multi(cr, uid, pricelist, products_by_qty_by_partner, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/product_variants_no_automatic_creation/models/pricelist.py", line 30, in _price_rule_get_multi
    pricelist, products_by_qty_by_partner)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/product/pricelist.py", line 336, in _price_rule_get_multi
    product_obj._price_get(cr, uid, [product], price_type.field, context=context)[product.id],
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/product/product.py", line 618, in _price_get
    res[product.id] = product[ptype] or 0.0
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5571, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: u'cost_price'
```

Un saludo.

**Comment by anajuaristi** [comment]
Por favor, @apesquero  indica los pasos para llegar al error. Si no, es imposible reproducirlo.

**Comment by apesquero** [comment]
Hola @anajuaristi 
1. Creamos un tipo de precio variante con el campo de producto "Variant cost price"
2. Creamos tarifa de venta basada en precio coste variante
3. Tenemos instalado sale_product_variants_types
4. Creamos un presupuesto con la tarifa anteriormente creada.
5. En la linea de pedido, asignamos un producto que contenga variantes...
6. Ahí produce el error.

Muchas gracias.
