### ISSUE TITLE
quality_control Module ~~ Unable to install odoo saas-6 version of! Error message as follows:

### ISSUE THREAD

**Issue by jaronemo** [odoomrp/odoomrp-wip#873]
Traceback (most recent call last):
  File "D:\odoo-saas-6\openerp\http.py", line 538, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo-saas-6\openerp\http.py", line 575, in dispatch
    result = self._call_function(*_self.params)
  File "D:\odoo-saas-6\openerp\http.py", line 311, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "D:\odoo-saas-6\openerp\service\model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "D:\odoo-saas-6\openerp\http.py", line 308, in checked_call
    return self.endpoint(_a, *_kw)
  File "D:\odoo-saas-6\openerp\http.py", line 813, in __call__
    return self.method(_args, *_kw)
  File "D:\odoo-saas-6\openerp\http.py", line 404, in response_wrap
    response = f(_args, *_kw)
  File "D:\odoo-saas-6\addons\web\controllers\main.py", line 968, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\odoo-saas-6\addons\web\controllers\main.py", line 956, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "D:\odoo-saas-6\openerp\api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\odoo-saas-6\openerp\addons\base\module\module.py", line 453, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "D:\odoo-saas-6\openerp\api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\odoo-saas-6\openerp\addons\base\module\module.py", line 501, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "D:\odoo-saas-6\openerp\modules\registry.py", line 371, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\odoo-saas-6\openerp\modules\loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "D:\odoo-saas-6\openerp\modules\loading.py", line 254, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "D:\odoo-saas-6\openerp\modules\loading.py", line 175, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "D:\odoo-saas-6\openerp\modules\loading.py", line 117, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\odoo-saas-6\openerp\tools\convert.py", line 863, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\odoo-saas-6\openerp\tools\convert.py", line 950, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\odoo-saas-6\openerp\tools\convert.py", line 813, in parse
    self.parse(rec, mode)
  File "D:\odoo-saas-6\openerp\tools\convert.py", line 816, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "D:\odoo-saas-6\openerp\tools\convert.py", line 642, in _tag_record
    model = self.pool[rec_model]
  File "D:\odoo-saas-6\openerp\modules\registry.py", line 102, in __getitem__
    return self.models[model_name]
ParseError: "ir.sequence.type" while parsing file:/D:/odoo-saas-6/addons/quality_control/data/quality_control_data.xml:14, near
<record id="seq_type_qc_inspection" model="ir.sequence.type">
            <field name="name">Quality inspection</field>
            <field name="code">qc.inspection</field>
        </record>

**Comment by pedrobaeza** [comment]
These modules are for v8, not saas-6, so they are not going to work in it.
