### ISSUE TITLE
Traceback al pulsar el botón crear niveles del plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#896]
Pasos:
Hemos vendido un producto MTO / manufacture
Se ha creado el abastecimiento pero NO lo hemos ejecutado
Hemos llevado el abastecimiento al plan
Pulsamos botón desglose por niveles y nos ha dado el traceback

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/procurement_plan_mrp/models/procurement.py", line 81, in button_create_lower_levels
    sorted_boms[0])
  File "/opt/odoo/v8/odoomrp-wip/procurement_plan_mrp/models/procurement.py", line 171, in _calculate_bom_line_details
    procurement)
  File "/opt/odoo/v8/odoomrp-wip/procurement_plan_mrp/models/procurement.py", line 178, in _create_procurement_from_bom_line
    procurement)
  File "/opt/odoo/v8/odoomrp-wip/procurement_plan_mrp/models/procurement.py", line 213, in _prepare_procurements_vals
    vals.update(procurement_obj.onchange_product_id(product.id)['value'])
KeyError: 'value'

```

**Comment by alfredoavanzosc** [comment]
Realizado, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/897

**Comment by alfredoavanzosc** [comment]
Pedro ya ha realizado el MERGE
