### ISSUE TITLE
Error on web_site_sale 

### ISSUE THREAD

**Issue by pauloneda** [odoomrp/odoomrp-wip#981]
module: sale_product_variants
version: 8.0

**Steps to reproduce**
- Create product variant

**Current behavior**
    Web Site Sale 
     TypeError: product_id_change() got an unexpected keyword argument 'product'

**Expected behavior**
  cart_update

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 684, in dispatch
    r = self._call_function(*_self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/website_sale/controllers/main.py", line 338, in cart_update
    request.website.sale_get_order(force_create=1)._cart_update(product_id=int(product_id), add_qty=float(add_qty), set_qty=float(set_qty))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/website_sale/models/sale_order.py", line 87, in _cart_update
    values = self._website_product_id_change(cr, uid, ids, so.id, product_id, qty=1, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/addons/website_sale/models/sale_order.py", line 55, in _website_product_id_change
    context=dict(context or {}, company_id=so.company_id.id)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3114711-8-0-1869af/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
TypeError: product_id_change() got an unexpected keyword argument 'product'

**Comment by pedrobaeza** [comment]
Thanks for reporting!
