### ISSUE TITLE
Error en producción "got an unexpected keyword argument 'amount'"

### ISSUE THREAD

**Issue by jmoderp** [odoomrp/odoomrp-wip#987]
Hola @pedrobaeza:

Tras la actualización de anoche no puedo “cerrar” las órdenes de producción. Te detallo el error  que me ha salido y la secuencia de pasos dada hasta su aparición. 

Como ya tengo creada la lista de materiales y la ruta de producción o proceso productivo, ya que las uso continuamente en las pruebas, voy a reproducir el error con los mínimos  pasos:

Creo una orden desde producción y fijo el producto a fabricar, pongo la cantidad de producto y doy a Guardar. A continuación pincho   **Confirmar producción** y como las materias primas tienen BUY y Make to order voy a gestionar la compra para obtener disponible. Confirmo los pedidos de compra (dos proveedores), recibo los productos y  transfiero las materias primas  e, incluso creo las facturas del proveedor dejándolas pendiente de pago.

Vuelvo a la orden que está esperando las materias primas en la barra de estado de la Header y en espera  **Comprobar disponibilidad** de  tener realizada la trasferencia de la productos de la compra.

Me pone las flechas verdes de proceder a consumir en la pestaña de productos a consumir, pero accedo directamente **Fabricar** a la barra de actuaciones de cabecera y pincho sobre ella:
Me aparece la ventana con los productos a consumir y la cantidad de producto terminado y Picho en Confirmar.

![ventana fabrica](https://cloud.githubusercontent.com/assets/14217386/9790615/48e92a2e-57d7-11e5-81c7-83d9ac52f8a2.PNG)

Inmediatamente me sale el error de Odoo, que reproduzco íntegramente a continuación:

```
--------------------------------------------------------------------------------------------------------------------------
**Odoo Server Error**:

Traceback (most recent call last):
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/common/openerp/v8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/common/openerp/v8/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/common/openerp/v8/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/addons/mrp/wizard/mrp_product_produce.py", line 123, in do_produce
    data.product_qty, data.mode, data, context=context)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/0512_plaesa_openerp/oca/quality_control_mrp/models/mrp_production.py", line 27, in action_produce
    production_id, production_qty, production_mode, wiz=wiz)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/0512_plaesa_openerp/oca/quality_control_mrp/models/mrp_production.py", line 33, in action_produce
    production_id, production_qty, production_mode, wiz=wiz)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/addons/mrp/mrp.py", line 1012, in action_produce
    restrict_lot_id=consume['lot_id'], consumed_for=main_production_move, context=context)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/0512_plaesa_openerp/oca/mrp_production_real_costs/models/stock_move.py", line 75, in action_consume
    amount=(-price * record.product_qty))
  File "/opt/odoo/common/openerp/v8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: _prepare_cost_analytic_line() got an unexpected keyword argument 'amount'


---------------------------------------------oooooOOOOOooooo------------------------------------------------
```

Quedo a la espera de tus noticias.

Un cordial saludo.

**Comment by pedrobaeza** [comment]
Actualiza a la última versión (en concreto, el commit https://github.com/odoomrp/odoomrp-wip/commit/cc7ac1b31b0825d10d4b49fa60a5b0088749d959), que lo resuelve.

**Comment by jmoderp** [comment]
@antespi Por favor Antonio, la incidencia de producción ya está resuelta puedes  actualizar donde proceda.

Gracias.
