### ISSUE TITLE
Quality Control - No Triggers

### ISSUE THREAD

**Issue by diiman2000** [odoomrp/odoomrp-wip#994]
Hi, Your app is great, but there is one issue am having
There are no triggers to define under the product template, when you click on the dropdwon nothing shows up. Please is there something i need to do to enable the triggers show just like in your youtube video (https://www.youtube.com/watch?v=FmGkwtgSVww).
Thanks.
Note. I have followed all the due process in the video but still no triggers to set

**Comment by pedrobaeza** [comment]
You need to install quality_control_stock or quality_control_mrp to have these triggers.

**Comment by diiman2000** [comment]
Thanks for you fast reply. I just want to ask a question. can the triggers be made before transfering the products to stock. so for example if there is something wrong, you wont have already transfered the product.
Thanks

**Comment by anajuaristi** [comment]
Define reception in 2 steps, so you will receive on first "temporal" location, as "quality" or "input" location before moving to stock but conceptually at less one move has to be done, since it's mandatory you receive somewhere the material before you can test it,

**Comment by diiman2000** [comment]
Hi,
There is an error when set test is clicked, After following the youtube video ( https://www.youtube.com/watch?v=FmGkwtgSVww).
I get the error below.

Traceback (most recent call last):
File "/opt/odoo1/odoo1-server/openerp/http.py", line 500, in handle_exception
return super(JsonRequest, self).handle_exception(exception)
File "/opt/odoo1/odoo1-server/openerp/http.py", line 517, in dispatch
result = self._call_function(*self.params)
File "/opt/odoo1/odoo1-server/openerp/http.py", line 283, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/service/model.py", line 113, in wrapper
return f(dbname, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/http.py", line 280, in checked_call
return self.endpoint(a, *kw)
File "/opt/odoo1/odoo1-server/openerp/http.py", line 733, in __call
return self.method(args, *kw)
File "/opt/odoo1/odoo1-server/openerp/http.py", line 376, in response_wrap
response = f(args, *kw)
File "/opt/odoo1/odoo1-server/addons/web/controllers/main.py", line 944, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo1/odoo1-server/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo1/odoo1-server/addons/mail/mail_thread.py", line 427, in write
result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 360, in old_api
result = method(recs, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/models.py", line 3693, in write
self._write(old_vals)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 235, in wrapper
return new_api(self, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 552, in new_api
result = method(self._model, cr, uid, self.ids, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/models.py", line 3792, in _write
self._check_selection_field_value(cr, user, field, vals[field], context=context)
File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo1/odoo1-server/openerp/models.py", line 2299, in _check_selection_field_value
elif val in dict(self._columns[field].selection(self, cr, uid, context=context)):
File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
TypeError: old_api() takes at least 4 arguments (3 given)

**Comment by pedrobaeza** [comment]
The error is due to an outdated installation
