### ISSUE TITLE
Quality Control - Error On Set Test

### ISSUE THREAD

**Issue by diiman2000** [odoomrp/odoomrp-wip#995]
Hi,
There is an error when set test is clicked, After following the youtube video.
I get the error below.

Traceback (most recent call last):
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo1/odoo1-server/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo1/odoo1-server/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo1/odoo1-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/addons/mail/mail_thread.py", line 427, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/models.py", line 3792, in _write
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo1/odoo1-server/openerp/models.py", line 2299, in _check_selection_field_value
    elif val in dict(self._columns[field].selection(self, cr, uid, context=context)):
  File "/opt/odoo1/odoo1-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
TypeError: old_api() takes at least 4 arguments (3 given)

**Comment by pedrobaeza** [comment]
That error is due to your Odoo/OCB installation that contains a problem in code, so check latest version of code, and if not, please put an issue on Odoo, not here.
